export const jobData = [
    {
        _id: "15d8fd58",
        jobTitle: "Front End Development in ReactJS",
        companyName: "Triple W Solutions",
        category: "front end development",
        office: true,
        partTime: true,
        location: "Delhi",
        starDate: "Immediately",
        duration: "6 Months",
        stippend: "35000",
        apply: "25 Feb 2022",
        jobType: "intership",
        applyCount: "451",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "5"
    },
    {
        _id: "8f7d8fd8f",
        jobTitle: "Front End Development in angular",
        companyName: "Triple W Solutions",
        category: "front end development",
        office: true,
        partTime: false,
        location: "kolkata",
        starDate: "Immediately",
        duration: "3 Months",
        stippend: "5000",
        apply: "25 Feb 2022",
        jobType: "intership",
        applyCount: "47",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "2"
    },
    {
        _id: "7d7fd25fdf",
        jobTitle: "Front End Development in vuejs",
        companyName: "TaskPlanet",
        category: "back end development",
        office: true,
        partTime: true,
        location: "Delhi",
        starDate: "Immediately",
        duration: "2 Months",
        stippend: "6000",
        apply: "18 Feb 2022",
        jobType: "intership",
        applyCount: "87",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "9"
    },
    {
        _id: "fd5df7d4f7",
        jobTitle: "MERN Stack developer",
        companyName: "TaskPlanet",
        category: "front end development",
        office: true,
        partTime: true,
        location: "mumbai",
        starDate: "Immediately",
        duration: "12 Months",
        stippend: "10000",
        apply: "20 Feb 2022",
        jobType: "intership",
        applyCount: "97",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "10"
    },
    {
        _id: "7sf5d5f4sfde",
        jobTitle: "ReactJS developer",
        companyName: "Stack Learner",
        category: "full stack development",
        office: true,
        partTime: false,
        location: "kolkata",
        starDate: "Immediately",
        duration: "6 Months",
        stippend: "6000",
        apply: "21 Feb 2022",
        jobType: "intership with job offer",
        applyCount: "26",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "1"
    },
    {
        _id: "878d5sfdsr6",
        jobTitle: "Web Developer",
        companyName: "TaskPlanet",
        category: "full stack development",
        office: true,
        partTime: false,
        location: "Delhi",
        starDate: "Immediately",
        duration: "4 Months",
        stippend: "6500",
        apply: "16 Feb 2022",
        jobType: "intership",
        applyCount: "47",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "3"
    },
    {
        _id: "f7d4fusyer7du",
        jobTitle: "mern developer",
        companyName: "TaskPlanet",
        category: "full stack development",
        office: true,
        partTime: true,
        location: "Delhi",
        starDate: "Immediately",
        duration: "12 Months",
        stippend: "1000",
        apply: "19 Feb 2022",
        jobType: "intership",
        applyCount: "47",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "10"
    },
    {
        _id: "7sd55fs8rs9r",
        jobTitle: "front end developer",
        companyName: "TaskPlanet",
        category: "back end development",
        office: true,
        partTime: true,
        location: "Delhi",
        starDate: "Immediately",
        duration: "1 Month",
        stippend: "4000",
        apply: "28 Feb 2022",
        jobType: "intership",
        applyCount: "87",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "7"
    },
    {
        _id: "9d7fs77er7sr",
        jobTitle: "back end developer",
        companyName: "programming hero",
        category: "back end development",
        office: true,
        partTime: true,
        location: "Delhi",
        starDate: "Immediately",
        duration: "24 Months",
        stippend: "15000",
        apply: "28 Feb 2022",
        jobType: "intership",
        applyCount: "67",
        companyDetails: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum, quo quam. Eius, modi, earum repudiandae ex facilis voluptate eos quo repellat id esse, cupiditate numquam sunt saepe quae voluptas dolorem.",
        skills: ["Reactjs", "html", "mern", "nodejs"],
        vacancy: "7"
    },
]